name: discover_printers
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  charset_converter:
  cupertino_icons:
  esc_pos_printer_plus:
    path: ../
  esc_pos_utils_plus: 
  flutter:
    sdk: flutter
  image: ^4.1.3
  intl: ^0.18.1
  path_provider: ^2.1.1
  ping_discover_network_plus: ^0.0.1
  qr_flutter:
 
dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/rabbit_black.jpg
